// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ZLHX75qLH_mwLYFF_YwZwNzxqhaZ4Tg',
    appId: '1:904098371260:web:20b4a703781720684322b9',
    messagingSenderId: '904098371260',
    projectId: 'hospitalmanagement-7605b',
    authDomain: 'hospitalmanagement-7605b.firebaseapp.com',
    storageBucket: 'hospitalmanagement-7605b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPEQi9SC1ZvJuRYXCtqaJ4MaCu4mX6HLc',
    appId: '1:904098371260:android:333a17454480f28c4322b9',
    messagingSenderId: '904098371260',
    projectId: 'hospitalmanagement-7605b',
    storageBucket: 'hospitalmanagement-7605b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx7CJkUts-mQSCu2xQvZwCVrc0k9rXd0g',
    appId: '1:904098371260:ios:0af947e63d0f35304322b9',
    messagingSenderId: '904098371260',
    projectId: 'hospitalmanagement-7605b',
    storageBucket: 'hospitalmanagement-7605b.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx7CJkUts-mQSCu2xQvZwCVrc0k9rXd0g',
    appId: '1:904098371260:ios:0af947e63d0f35304322b9',
    messagingSenderId: '904098371260',
    projectId: 'hospitalmanagement-7605b',
    storageBucket: 'hospitalmanagement-7605b.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ZLHX75qLH_mwLYFF_YwZwNzxqhaZ4Tg',
    appId: '1:904098371260:web:ae0184cc2e03209b4322b9',
    messagingSenderId: '904098371260',
    projectId: 'hospitalmanagement-7605b',
    authDomain: 'hospitalmanagement-7605b.firebaseapp.com',
    storageBucket: 'hospitalmanagement-7605b.firebasestorage.app',
  );
}
